(function () {

    let cities= [
        {
            "Name": "Tokyo",
            "Lat": 35.6850,
            "Long": 139.7514,
            "Country": "Japan",
            "Abbreviation": "JPN",
            "CapitalStatus": "primary",
            "Population": 35676000
        }, {
            "Name": "New York",
            "Lat": 40.6943,
            "Long": -73.9249,
            "Country": "United States",
            "Abbreviation": "USA",
            "CapitalStatus": "NA",
            "Population": 19354922
        }, {
            "Name": "Mexico City",
            "Lat": 19.4424,
            "Long": -99.1310,
            "Country": "Mexico",
            "Abbreviation": "MEX",
            "CapitalStatus": "primary",
            "Population": 19028000
        }, {
            "Name": "Los Angeles",
            "Lat": 34.1139,
            "Long": -118.4068,
            "Country": "United States",
            "Abbreviation": "USA",
            "CapitalStatus": "NA",
            "Population": 12815475
        }, {
            "Name": "Zhongli",
            "Lat": 24.9650,
            "Long": 121.2168,
            "Country": "Taiwan",
            "Abbreviation": "TWN",
            "CapitalStatus": "NA",
            "Population": 1632616
        }, {
            "Name": "Handan",
            "Lat": 36.5800,
            "Long": 114.4800,
            "Country": "China",
            "Abbreviation": "CHN",
            "CapitalStatus": "NA",
            "Population": 1631000
        }, {
            "Name": "Tai'an",
            "Lat": 36.2000,
            "Long": 117.1201,
            "Country": "China",
            "Abbreviation": "CHN",
            "CapitalStatus": "NA",
            "Population": 1629000
        }, {
            "Name": "Kansas City",
            "Lat": 39.1239,
            "Long": -94.5541,
            "Country": "United States",
            "Abbreviation": "USA",
            "CapitalStatus": "NA",
            "Population": 1615621
        }, {
            "Name": "Yaounde",
            "Lat": 3.8667,
            "Long": 11.5167,
            "Country": "Cameroon",
            "fldAbbreviation": "CMR",
            "fldCapitalStatus": "primary",
            "fldPopulation": 1611000
        }, {
            "fldName": "Agra",
            "fldLat": 27.1704,
            "fldLong": 78.0150,
            "fldCountry": "India",
            "fldAbbreviation": "IND",
            "fldCapitalStatus": "NA",
            "fldPopulation": 1592000
        }, {
            "fldName": "La Paz",
            "fldLat": -16.4980,
            "fldLong": -68.1500,
            "fldCountry": "Bolivia",
            "fldAbbreviation": "BOL",
            "fldCapitalStatus": "primary",
            "fldPopulation": 1590000
        }, {
            "fldName": "Kalyan",
            "fldLat": 19.2502,
            "fldLong": 73.1602,
            "fldCountry": "India",
            "fldAbbreviation": "IND",
            "fldCapitalStatus": "NA",
            "fldPopulation": 1576614
        }, {
            "fldName": "Abuja",
            "fldLat": 9.0833,
            "fldLong": 7.5333,
            "fldCountry": "Nigeria",
            "fldAbbreviation": "NGA",
            "fldCapitalStatus": "primary",
            "fldPopulation": 1576000
        }, {
            "fldName": "Harare",
            "fldLat": -17.8178,
            "fldLong": 31.0447,
            "fldCountry": "Zimbabwe",
            "fldAbbreviation": "ZWE",
            "fldCapitalStatus": "primary",
            "fldPopulation": 1572000
        }, {
            "fldName": "Xiantao",
            "fldLat": 30.3704,
            "fldLong": 113.4400,
            "fldCountry": "China",
            "fldAbbreviation": "CHN",
            "fldCapitalStatus": "NA",
            "fldPopulation": 1556000
        }, {
            "fldName": "Weifang",
            "fldLat": 36.7204,
            "fldLong": 119.1001,
            "fldCountry": "China",
            "fldAbbreviation": "CHN",
            "fldCapitalStatus": "NA",
            "fldPopulation": 1553000
        }, {
            "fldName": "Xinyang",
            "fldLat": 32.1304,
            "fldLong": 114.0700,
            "fldCountry": "China",
            "fldAbbreviation": "CHN",
            "fldCapitalStatus": "NA",
            "fldPopulation": 1541000
        }, {
            "fldName": "Vishakhapatnam",
            "fldLat": 17.7300,
            "fldLong": 83.3050,
            "fldCountry": "India",
            "fldAbbreviation": "IND",
            "fldCapitalStatus": "NA",
            "fldPopulation": 1529000
        }, {
            "fldName": "Kochi",
            "fldLat": 10.0150,
            "fldLong": 76.2239,
            "fldCountry": "India",
            "fldAbbreviation": "IND",
            "fldCapitalStatus": "NA",
            "fldPopulation": 1519000
        }, {
            "fldName": "Montevideo",
            "fldLat": -34.8580,
            "fldLong": -56.1711,
            "fldCountry": "Uruguay",
            "fldAbbreviation": "URY",
            "fldCapitalStatus": "primary",
            "fldPopulation": 1513000
        }, {
            "fldName": "Niteroi",
            "fldLat": -22.9000,
            "fldLong": -43.1000,
            "fldCountry": "Brazil",
            "fldAbbreviation": "BRA",
            "fldCapitalStatus": "NA",
            "fldPopulation": 1500513
        }, {
            "fldName": "Bamako",
            "fldLat": 12.6500,
            "fldLong": -8.0000,
            "fldCountry": "Mali",
            "fldAbbreviation": "MLI",
            "fldCapitalStatus": "primary",
            "fldPopulation": 1494000
        }, {
            "fldName": "Conakry",
            "fldLat": 9.5315,
            "fldLong": -13.6802,
            "fldCountry": "Guinea",
            "fldAbbreviation": "GIN",
            "fldCapitalStatus": "primary",
            "fldPopulation": 1494000
        }, {
            "fldName": "Virginia Beach",
            "fldLat": 36.7335,
            "fldLong": -76.0435,
            "fldCountry": "United States",
            "fldAbbreviation": "USA",
            "fldCapitalStatus": "NA",
            "fldPopulation": 1480383
        }, {
            "fldName": "Nasik",
            "fldLat": 20.0004,
            "fldLong": 73.7800,
            "fldCountry": "India",
            "fldAbbreviation": "IND",
            "fldCapitalStatus": "NA",
            "fldPopulation": 1473000
        }, {
            "fldName": "Fushun",
            "fldLat": 41.8654,
            "fldLong": 123.8700,
            "fldCountry": "China",
            "fldAbbreviation": "CHN",
            "fldCapitalStatus": "NA",
            "fldPopulation": 1470000
        }, {
            "fldName": "Charlotte",
            "fldLat": 35.2079,
            "fldLong": -80.8304,
            "fldCountry": "United States",
            "fldAbbreviation": "USA",
            "fldCapitalStatus": "NA",
            "fldPopulation": 1467362
        }, {
            "fldName": "Phnom Penh",
            "fldLat": 11.5500,
            "fldLong": 104.9166,
            "fldCountry": "Cambodia",
            "fldAbbreviation": "KHM",
            "fldCapitalStatus": "primary",
            "fldPopulation": 1466000
        }, {
            "fldName": "Hyderabad City",
            "fldLat": 25.3800,
            "fldLong": 68.3750,
            "fldCountry": "Pakistan",
            "fldAbbreviation": "PAK",
            "fldCapitalStatus": "NA",
            "fldPopulation": 1459000
        }, {
            "fldName": "Bronx",
            "fldLat": 40.8501,
            "fldLong": -73.8662,
            "fldCountry": "United States",
            "fldAbbreviation": "USA",
            "fldCapitalStatus": "NA",
            "fldPopulation": 1455720
        }, {
            "fldName": "Lome",
            "fldLat": 6.1319,
            "fldLong": 1.2228,
            "fldCountry": "Togo",
            "fldAbbreviation": "TGO",
            "fldCapitalStatus": "primary",
            "fldPopulation": 1452000
        }, {
            "fldName": "Huainan",
            "fldLat": 32.6300,
            "fldLong": 116.9800,
            "fldCountry": "China",
            "fldAbbreviation": "CHN",
            "fldCapitalStatus": "NA",
            "fldPopulation": 1451000
        }, {
            "fldName": "Doha",
            "fldLat": 25.2866,
            "fldLong": 51.5330,
            "fldCountry": "Qatar",
            "fldAbbreviation": "QAT",
            "fldCapitalStatus": "primary",
            "fldPopulation": 1450000
        }, {
            "fldName": "Kuala Lumpur",
            "fldLat": 3.1667,
            "fldLong": 101.7000,
            "fldCountry": "Malaysia",
            "fldAbbreviation": "MYS",
            "fldCapitalStatus": "primary",
            "fldPopulation": 1448000
        }, {
            "fldName": "Maputo",
            "fldLat": -25.9553,
            "fldLong": 32.5892,
            "fldCountry": "Mozambique",
            "fldAbbreviation": "MOZ",
            "fldCapitalStatus": "primary",
            "fldPopulation": 1446000
        }, {
            "fldName": "Kawanakajima",
            "fldLat": 35.5300,
            "fldLong": 139.7050,
            "fldCountry": "Japan",
            "fldAbbreviation": "JPN",
            "fldCapitalStatus": "NA",
            "fldPopulation": 1437266
        }, {
            "fldName": "San Salvador",
            "fldLat": 13.7100,
            "fldLong": -89.2030,
            "fldCountry": "El Salvador",
            "fldAbbreviation": "SLV",
            "fldCapitalStatus": "primary",
            "fldPopulation": 1433000
        }, {
            "fldName": "Kampala",
            "fldLat": 0.3167,
            "fldLong": 32.5833,
            "fldCountry": "Uganda",
            "fldAbbreviation": "UGA",
            "fldCapitalStatus": "primary",
            "fldPopulation": 1420000
        }, {
            "fldName": "The Hague",
            "fldLat": 52.0800,
            "fldLong": 4.2700,
            "fldCountry": "Netherlands",
            "fldAbbreviation": "NLD",
            "fldCapitalStatus": "primary",
            "fldPopulation": 1406000
        }, {
            "fldName": "Meerut",
            "fldLat": 29.0004,
            "fldLong": 77.7000,
            "fldCountry": "India",
            "fldAbbreviation": "IND",
            "fldCapitalStatus": "NA",
            "fldPopulation": 1398000
        }, {
            "fldName": "Faridabad",
            "fldLat": 28.4333,
            "fldLong": 77.3167,
            "fldCountry": "India",
            "fldAbbreviation": "IND",
            "fldCapitalStatus": "NA",
            "fldPopulation": 1394000
        }, {
            "fldName": "Milwaukee",
            "fldLat": 43.0642,
            "fldLong": -87.9673,
            "fldCountry": "United States",
            "fldAbbreviation": "USA",
            "fldCapitalStatus": "NA",
            "fldPopulation": 1377808
        }, {
            "fldName": "Brazzaville",
            "fldLat": -4.2592,
            "fldLong": 15.2847,
            "fldCountry": "Congo (Brazzaville)",
            "fldAbbreviation": "COG",
            "fldCapitalStatus": "primary",
            "fldPopulation": 1355000
        }, {
            "fldName": "Varanasi",
            "fldLat": 25.3300,
            "fldLong": 83.0000,
            "fldCountry": "India",
            "fldAbbreviation": "IND",
            "fldCapitalStatus": "NA",
            "fldPopulation": 1352000
        }, {
            "fldName": "Yiyang",
            "fldLat": 28.6004,
            "fldLong": 112.3300,
            "fldCountry": "China",
            "fldAbbreviation": "CHN",
            "fldCapitalStatus": "NA",
            "fldPopulation": 1352000
        }, {
            "fldName": "Ghaziabad",
            "fldLat": 28.6604,
            "fldLong": 77.4084,
            "fldCountry": "India",
            "fldAbbreviation": "IND",
            "fldCapitalStatus": "NA",
            "fldPopulation": 1341000
        }, {
            "fldName": "Pretoria",
            "fldLat": -25.7069,
            "fldLong": 28.2294,
            "fldCountry": "South Africa",
            "fldAbbreviation": "ZAF",
            "fldCapitalStatus": "primary",
            "fldPopulation": 1338000
        }, {
            "fldName": "Lusaka",
            "fldLat": -15.4166,
            "fldLong": 28.2833,
            "fldCountry": "Zambia",
            "fldAbbreviation": "ZMB",
            "fldCapitalStatus": "primary",
            "fldPopulation": 1328000
        }, {
            "fldName": "Asansol",
            "fldLat": 23.6833,
            "fldLong": 86.9833,
            "fldCountry": "India",
            "fldAbbreviation": "IND",
            "fldCapitalStatus": "NA",
            "fldPopulation": 1328000
        }, {
            "fldName": "Jamshedpur",
            "fldLat": 22.7875,
            "fldLong": 86.1975,
            "fldCountry": "India",
            "fldAbbreviation": "IND",
            "fldCapitalStatus": "NA",
            "fldPopulation": 1300000
        }, {
            "fldName": "Madura",
            "fldLat": 9.9200,
            "fldLong": 78.1200,
            "fldCountry": "India",
            "fldAbbreviation": "IND",
            "fldCapitalStatus": "NA",
            "fldPopulation": 1294000
        }, {
            "fldName": "Jabalpur",
            "fldLat": 23.1751,
            "fldLong": 79.9551,
            "fldCountry": "India",
            "fldAbbreviation": "IND",
            "fldCapitalStatus": "NA",
            "fldPopulation": 1285000
        }, {
            "fldName": "San Jose",
            "fldLat": 9.9350,
            "fldLong": -84.0841,
            "fldCountry": "Costa Rica",
            "fldAbbreviation": "CRI",
            "fldCapitalStatus": "primary",
            "fldPopulation": 1284000
        }, {
            "fldName": "Panama City",
            "fldLat": 8.9680,
            "fldLong": -79.5330,
            "fldCountry": "Panama",
            "fldAbbreviation": "PAN",
            "fldCapitalStatus": "primary",
            "fldPopulation": 1281000
        }, {
            "fldName": "Stockholm",
            "fldLat": 59.3508,
            "fldLong": 18.0973,
            "fldCountry": "Sweden",
            "fldAbbreviation": "SWE",
            "fldCapitalStatus": "primary",
            "fldPopulation": 1264000
        }, {
            "fldName": "Huaiyin",
            "fldLat": 33.5800,
            "fldLong": 119.0300,
            "fldCountry": "China",
            "fldAbbreviation": "CHN",
            "fldCapitalStatus": "NA",
            "fldPopulation": 1264000
        }, {
            "fldName": "Rajkot",
            "fldLat": 22.3100,
            "fldLong": 70.8000,
            "fldCountry": "India",
            "fldAbbreviation": "IND",
            "fldCapitalStatus": "NA",
            "fldPopulation": 1260000
        }, {
            "fldName": "Dhanbad",
            "fldLat": 23.8004,
            "fldLong": 86.4200,
            "fldCountry": "India",
            "fldAbbreviation": "IND",
            "fldCapitalStatus": "NA",
            "fldPopulation": 1246000
        }, {
            "fldName": "Shuangshui",
            "fldLat": 26.5944,
            "fldLong": 104.8333,
            "fldCountry": "China",
            "fldAbbreviation": "CHN",
            "fldCapitalStatus": "NA",
            "fldPopulation": 1221000
        }, {
            "fldName": "Gaozhou",
            "fldLat": 21.9204,
            "fldLong": 110.8700,
            "fldCountry": "China",
            "fldAbbreviation": "CHN",
            "fldCapitalStatus": "NA",
            "fldPopulation": 1217715
        }, {
            "fldName": "Amritsar",
            "fldLat": 31.6400,
            "fldLong": 74.8700,
            "fldCountry": "India",
            "fldAbbreviation": "IND",
            "fldCapitalStatus": "NA",
            "fldPopulation": 1212000
        }, {
            "fldName": "Vila Velha",
            "fldLat": -20.3676,
            "fldLong": -40.3180,
            "fldCountry": "Brazil",
            "fldAbbreviation": "BRA",
            "fldCapitalStatus": "NA",
            "fldPopulation": 1209091
        }, {
            "fldName": "Vila Velha",
            "fldLat": 3.2167,
            "fldLong": -51.2167,
            "fldCountry": "Brazil",
            "fldAbbreviation": "BRA",
            "fldCapitalStatus": "NA",
            "fldPopulation": 1209091
        }, {
            "fldName": "Warangal",
            "fldLat": 18.0100,
            "fldLong": 79.5800,
            "fldCountry": "India",
            "fldAbbreviation": "IND",
            "fldCapitalStatus": "NA",
            "fldPopulation": 1203853
        }, {
            "fldName": "Allahabad",
            "fldLat": 25.4550,
            "fldLong": 81.8400,
            "fldCountry": "India",
            "fldAbbreviation": "IND",
            "fldCapitalStatus": "NA",
            "fldPopulation": 1201000
        }, {
            "fldName": "Jining",
            "fldLat": 35.4004,
            "fldLong": 116.5500,
            "fldCountry": "China",
            "fldAbbreviation": "CHN",
            "fldCapitalStatus": "NA",
            "fldPopulation": 1186000
        }, {
            "fldName": "Sofia",
            "fldLat": 42.6833,
            "fldLong": 23.3167,
            "fldCountry": "Bulgaria",
            "fldAbbreviation": "BGR",
            "fldCapitalStatus": "primary",
            "fldPopulation": 1185000
        }, {
            "fldName": "Prague",
            "fldLat": 50.0833,
            "fldLong": 14.4660,
            "fldCountry": "Czechia",
            "fldAbbreviation": "CZE",
            "fldCapitalStatus": "primary",
            "fldPopulation": 1162000
        }, {
            "fldName": "Leshan",
            "fldLat": 29.5671,
            "fldLong": 103.7333,
            "fldCountry": "China",
            "fldAbbreviation": "CHN",
            "fldCapitalStatus": "NA",
            "fldPopulation": 1157000
        }, {
            "fldName": "Jacksonville",
            "fldLat": 30.3322,
            "fldLong": -81.6749,
            "fldCountry": "United States",
            "fldAbbreviation": "USA",
            "fldCapitalStatus": "NA",
            "fldPopulation": 1156291
        }, {
            "fldName": "Ouagadougou",
            "fldLat": 12.3703,
            "fldLong": -1.5247,
            "fldCountry": "Burkina Faso",
            "fldAbbreviation": "BFA",
            "fldCapitalStatus": "primary",
            "fldPopulation": 1149000
        }, {
            "fldName": "Ottawa",
            "fldLat": 45.4167,
            "fldLong": -75.7000,
            "fldCountry": "Canada",
            "fldAbbreviation": "CAN",
            "fldCapitalStatus": "primary",
            "fldPopulation": 1145000
        }, {
            "fldName": "Bezwada",
            "fldLat": 16.5200,
            "fldLong": 80.6300,
            "fldCountry": "India",
            "fldAbbreviation": "IND",
            "fldCapitalStatus": "NA",
            "fldPopulation": 1137000
        }, {
            "fldName": "Newcastle",
            "fldLat": -32.8453,
            "fldLong": 151.8150,
            "fldCountry": "Australia",
            "fldAbbreviation": "AUS",
            "fldCapitalStatus": "NA",
            "fldPopulation": 1134616
        }, {
            "fldName": "Yulin",
            "fldLat": 22.6300,
            "fldLong": 110.1500,
            "fldCountry": "China",
            "fldAbbreviation": "CHN",
            "fldCapitalStatus": "NA",
            "fldPopulation": 1127000
        }, {
            "fldName": "Helsinki",
            "fldLat": 60.1756,
            "fldLong": 24.9341,
            "fldCountry": "Finland",
            "fldAbbreviation": "FIN",
            "fldCapitalStatus": "primary",
            "fldPopulation": 1115000
        }, {
            "fldName": "Aurangabad",
            "fldLat": 19.8957,
            "fldLong": 75.3203,
            "fldCountry": "India",
            "fldAbbreviation": "IND",
            "fldCapitalStatus": "NA",
            "fldPopulation": 1113000
        }, {
            "fldName": "Calgary",
            "fldLat": 51.0830,
            "fldLong": -114.0800,
            "fldCountry": "Canada",
            "fldAbbreviation": "CAN",
            "fldCapitalStatus": "NA",
            "fldPopulation": 1110000
        }, {
            "fldName": "Ciudad Nezahualcoyotl",
            "fldLat": 19.4100,
            "fldLong": -99.0300,
            "fldCountry": "Mexico",
            "fldAbbreviation": "MEX",
            "fldCapitalStatus": "NA",
            "fldPopulation": 1109363
        }, {
            "fldName": "Baoding",
            "fldLat": 38.8704,
            "fldLong": 115.4800,
            "fldCountry": "China",
            "fldAbbreviation": "CHN",
            "fldCapitalStatus": "NA",
            "fldPopulation": 1107000
        }, {
            "fldName": "Zigong",
            "fldLat": 29.4000,
            "fldLong": 104.7800,
            "fldCountry": "China",
            "fldAbbreviation": "CHN",
            "fldCapitalStatus": "NA",
            "fldPopulation": 1105000
        }, {
            "fldName": "Yerevan",
            "fldLat": 40.1812,
            "fldLong": 44.5136,
            "fldCountry": "Armenia",
            "fldAbbreviation": "ARM",
            "fldCapitalStatus": "primary",
            "fldPopulation": 1102000
        }, {
            "fldName": "Mogadishu",
            "fldLat": 2.0667,
            "fldLong": 45.3667,
            "fldCountry": "Somalia",
            "fldAbbreviation": "SOM",
            "fldCapitalStatus": "primary",
            "fldPopulation": 1100000
        }, {
            "fldName": "Tbilisi",
            "fldLat": 41.7250,
            "fldLong": 44.7908,
            "fldCountry": "Georgia",
            "fldAbbreviation": "GEO",
            "fldCapitalStatus": "primary",
            "fldPopulation": 1100000
        }, {
            "fldName": "Ankang",
            "fldLat": 32.6800,
            "fldLong": 109.0200,
            "fldCountry": "China",
            "fldAbbreviation": "CHN",
            "fldCapitalStatus": "NA",
            "fldPopulation": 1100000
        }, {
            "fldName": "Belgrade",
            "fldLat": 44.8186,
            "fldLong": 20.4680,
            "fldCountry": "Serbia",
            "fldAbbreviation": "SRB",
            "fldCapitalStatus": "primary",
            "fldPopulation": 1099000
        }, {
            "fldName": "Bhilai",
            "fldLat": 21.2167,
            "fldLong": 81.4333,
            "fldCountry": "India",
            "fldAbbreviation": "IND",
            "fldCapitalStatus": "NA",
            "fldPopulation": 1097000
        }, {
            "fldName": "Dushanbe",
            "fldLat": 38.5600,
            "fldLong": 68.7739,
            "fldCountry": "Tajikistan",
            "fldAbbreviation": "TJK",
            "fldCapitalStatus": "primary",
            "fldPopulation": 1086244
        }, {
            "fldName": "Copenhagen",
            "fldLat": 55.6786,
            "fldLong": 12.5635,
            "fldCountry": "Denmark",
            "fldAbbreviation": "DNK",
            "fldCapitalStatus": "primary",
            "fldPopulation": 1085000
        }, {
            "fldName": "Vereeniging",
            "fldLat": -26.6496,
            "fldLong": 27.9600,
            "fldCountry": "South Africa",
            "fldAbbreviation": "ZAF",
            "fldCapitalStatus": "NA",
            "fldPopulation": 1074000
        }, {
            "fldName": "Memphis",
            "fldLat": 35.1046,
            "fldLong": -89.9773,
            "fldCountry": "United States",
            "fldAbbreviation": "USA",
            "fldCapitalStatus": "NA",
            "fldPopulation": 1068873
        }, {
            "fldName": "Amman",
            "fldLat": 31.9500,
            "fldLong": 35.9333,
            "fldCountry": "Jordan",
            "fldAbbreviation": "JOR",
            "fldCapitalStatus": "primary",
            "fldPopulation": 1060000
        }, {
            "fldName": "Dublin",
            "fldLat": 53.3331,
            "fldLong": -6.2489,
            "fldCountry": "Ireland",
            "fldAbbreviation": "IRL",
            "fldCapitalStatus": "primary",
            "fldPopulation": 1059000
        }, {
            "fldName": "Solapur",
            "fldLat": 17.6704,
            "fldLong": 75.9000,
            "fldCountry": "India",
            "fldAbbreviation": "IND",
            "fldCapitalStatus": "NA",
            "fldPopulation": 1057000
        }, {
            "fldName": "Zhangjiakou",
            "fldLat": 40.8300,
            "fldLong": 114.9300,
            "fldCountry": "China",
            "fldAbbreviation": "CHN",
            "fldCapitalStatus": "NA",
            "fldPopulation": 1046000
        }, {
            "fldName": "Monrovia",
            "fldLat": 6.3106,
            "fldLong": -10.8048,
            "fldCountry": "Liberia",
            "fldAbbreviation": "LBR",
            "fldCapitalStatus": "primary",
            "fldPopulation": 1041000
        }, {
            "fldName": "Amsterdam",
            "fldLat": 52.3500,
            "fldLong": 4.9166,
            "fldCountry": "Netherlands",
            "fldAbbreviation": "NLD",
            "fldCapitalStatus": "primary",
            "fldPopulation": 1031000
        }, {
            "fldName": "Jerusalem",
            "fldLat": 31.7784,
            "fldLong": 35.2066,
            "fldCountry": "Israel",
            "fldAbbreviation": "ISR",
            "fldCapitalStatus": "primary",
            "fldPopulation": 1029300
        }, {
            "fldName": "New Orleans",
            "fldLat": 30.0687,
            "fldLong": -89.9288,
            "fldCountry": "United States",
            "fldAbbreviation": "USA",
            "fldCapitalStatus": "NA",
            "fldPopulation": 1029123
        }, {
            "fldName": "Guatemala City",
            "fldLat": 14.6211,
            "fldLong": -90.5270,
            "fldCountry": "Guatemala",
            "fldAbbreviation": "GTM",
            "fldCapitalStatus": "primary",
            "fldPopulation": 1024000
        }, {
            "fldName": "Port Elizabeth",
            "fldLat": -33.9700,
            "fldLong": 25.6000,
            "fldCountry": "South Africa",
            "fldAbbreviation": "ZAF",
            "fldCapitalStatus": "NA",
            "fldPopulation": 1021000
        }, {
            "fldName": "Hengyang",
            "fldLat": 26.8800,
            "fldLong": 112.5900,
            "fldCountry": "China",
            "fldAbbreviation": "CHN",
            "fldCapitalStatus": "NA",
            "fldPopulation": 1016000
        }, {
            "fldName": "Benxi",
            "fldLat": 41.3304,
            "fldLong": 123.7500,
            "fldCountry": "China",
            "fldAbbreviation": "CHN",
            "fldCapitalStatus": "NA",
            "fldPopulation": 1012000
        }, {
            "fldName": "Louisville",
            "fldLat": 38.1663,
            "fldLong": -85.6485,
            "fldCountry": "United States",
            "fldAbbreviation": "USA",
            "fldCapitalStatus": "NA",
            "fldPopulation": 1011696
        }, {
            "fldName": "Cologne",
            "fldLat": 50.9300,
            "fldLong": 6.9500,
            "fldCountry": "Germany",
            "fldAbbreviation": "DEU",
            "fldCapitalStatus": "NA",
            "fldPopulation": 1004000
        }, {
            "fldName": "Qinhuangdao",
            "fldLat": 39.9304,
            "fldLong": 119.6200,
            "fldCountry": "China",
            "fldAbbreviation": "CHN",
            "fldCapitalStatus": "NA",
            "fldPopulation": 1003000
        }
    ];
    console.log(cities);
    console.log("Hello");
    let table = document.querySelector("table");
    let TableHeadings = Object.keys(cities[0]);
    table.classList.add("table");
    generateTableHead(table, TableHeadings);
    generateTable(table, cities);

})();

function generateTableHead(table, TableHeadings) {
    let thead = table.createTHead();
    let row = thead.insertRow();
    for (let heading of TableHeadings) {
        let th = document.createElement("th");
        let text = document.createTextNode(heading);
        th.appendChild(text);
        row.appendChild(th);
    }
}

function generateTable(table, data) {
    for (let element of data) {
        let row = table.insertRow();
        for (key in element) {
            let cell = row.insertCell();
            let text = document.createTextNode(element[key]);
            cell.appendChild(text);
        }
    }
}